CONTENT_EXCERPT_WIDTH = 500
PUNISHMENT_REASON = 'Triggered honeypot channel.'
SOFTBAN_DELETE_MESSAGE_SECONDS = 5 * 60
DISCORD_MAX_DELETE_MESSAGE_SECONDS = 7 * 24 * 60 * 60
SCAN_DELETE_SECONDS_GRACE = 5
BAN_TRIGGER_MODULO = 3
BLOOM_MIN_EXPECTED_ITEMS = 1024
